[package]
name = "vizia_blur_test"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = "0.6.2"
vizia = { git = "https://github.com/vizia/vizia", branch = "main" }
winapi = { version = "0.3.9", features = ["winuser"] }
window-vibrancy = "0.6.0"
